language: ruby
notifications:
  email:
    on_success: change
    on_failure: always
rvm:
  - 1.9.3
  - 2.0.0
  - rbx-19mode
  - jruby-19mode
  - jruby-20mode
  - jruby-head
matrix:
  allow_failures:
