require_relative 'bitformat/field'
require_relative 'bitformat/stream'
require_relative 'bitformat/array'
require_relative 'bitformat/numeric'
require_relative 'bitformat/string'
require_relative 'bitformat/bitfield'
